version: 1
# 将信息传播到配置文件的跟日志记录器中
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    upgrade:
        format: "%(asctime)s -Loc %(filename)s -Pid %(process)d -%(name)s -%(levelname)s - %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        # 只在文件中记录INFO级别及以上的log
        level: INFO
        formatter: simple
        filename: ./logs/server_logs/info.log
        # 10MB
        maxBytes: 10485760
        #保留 20个log文件
        backupCount: 20
        encoding: utf8
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: upgrade
        filename: ./logs/server_logs/errors.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
    appiumapi_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: upgrade
        filename: ./logs/server_logs/server.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8

loggers:
    AppiumApi:
        level: DEBUG
        handlers: [info_file_handler]
        propagate: False
root:
    level: INFO
    handlers: [console,info_file_handler,error_file_handler]