version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    upgrade:
        format: "%(asctime)s [%(filename)s-%(funcName)s:%(lineno)d,p:%(process)d] %(name)s -%(levelname)s: %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: ${logs}/appiumApiInfo.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: upgrade
        filename: ${logs}/appiumApiErrors.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
    appiumbar_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: ${logs}/appiumBarInfo.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
    uiauto2bar_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: ${logs}/uiauto2BarInfo.log
        maxBytes: 10485760
        backupCount: 20
        encoding: utf8
root:
    level: INFO
    handlers: [console]
loggers:
    AppiumBar:
        level: INFO
        handlers: [ console,appiumbar_file_handler ]
        propagate: False
    <module.x>:
        level: INFO
        handlers: [ uiauto2bar_file_handler ]
        propagate: False
    Uiauto2Bar:
        level: INFO
        handlers: [ console,uiauto2bar_file_handler ]
        propagate: False